### ISSUE TITLE
Adding translations

### ISSUE THREAD

**Issue by dtygel** [tlovett1/feed-pull#16]
Hi,
   I've just translated the feed-pull.pot file and saved to feed-pull-pt_BR, but it doesn't get loaded. Is there anything that must be set in the plugin code to load the language files from the language set in the wordpress site?
   Ah: and how do I send you my translation to contribute to your plugin?
   Thanks,
          daniel

**Comment by tlovett1** [comment]
Great! You can open up a pull request against the develop branch or email me the po/mo files (taylor.lovett[at]10up).

**Comment by dtygel** [comment]
I've done the pull request: https://github.com/tlovett1/feed-pull/pull/17 .

But the translation doesn't seem to load: I still see everything in English, although my wordpress settings are pt_BR.
