### ISSUE TITLE
Suggestion: grab first image in content as featured image

### ISSUE THREAD

**Issue by dtygel** [tlovett1/feed-pull#19]
Hi,

I would like to make a suggestion, which I could try to help programming: In the feed source edition page, there could be an input called "XPath to grab featured image". Then the user can put a XPath, and feed pull will first see if the content is html or simply an url of an image. If it's HTML, feed pull will parse the first "img" tag and get the 'src' attribute. If it's only an url, this will be the image url.

Then feed pull would add this url as featured image for the posts loaded on each feed pull.

Is this interesting or under the scope of the plugin?

**Comment by tlovett1** [comment]
This would be a good feature. Pull requests welcome :) Right now you can accomplish this with the existing plugin hooks.
