### ISSUE TITLE
Feed titles not lining up with images

### ISSUE THREAD

**Issue by michaelwesolowski** [tlovett1/feed-pull#20]
Hello,
I have a question about Feed Pull- When there is more than one title appearing on a page a feed is pulling to and the title contains a featured image the titles do not line up with the images- Can you suggest a fix? See this example http://sttheresanewberlinny.org/bulletins
Thank you for your time.
Michael

**Comment by tlovett1** [comment]
Seems like some of your items don't have titles. Really this plugin is front end agnostic so this is something you will have to resolve in your theme. Sorry!

**Comment by michaelwesolowski** [comment]
Your comments are not very helpful for having created the thing. It it does not work as expected, why bother putting it out there?


---Michael
Call/text: 607-316-6271 
michaelwesolowski@yahoo.com
