### ISSUE TITLE
Get post tags from a comma separated XML term

### ISSUE THREAD

**Issue by fryswe** [tlovett1/feed-pull#26]
The XML feed provide the keywords/tags for a post like this:

<keywords>tag1, tag2, tag3, tag4</keywords>

I tried to use /keywords/text() and yes, I will get ONE tag like "tag1, tag2, tag3, tag4", but unfortunately Wordpress do not understand this term as four separate tags.

So, how could I extract the tags in a way Wordpress can handle them?

Best
Sebastian

**Comment by tlovett1** [comment]
You will need to write PHP to hook into the plugin unfortunately.
