### ISSUE TITLE
Mapping a field attribute?

### ISSUE THREAD

**Issue by nkals722** [tlovett1/feed-pull#27]
I know you can map an element such as <book>The Catcher in the Rye</book>

but are you able to reference the attribute of an element such as <person name="nick"></name>

In the above example I want to map the name attribute to a field. I cannot seem to find an answer to this. Is this existing functionality? I have tried mapping person["name"] but it doesn't map anything.

**Comment by tlovett1** [comment]
http://stackoverflow.com/questions/1529038/how-to-reference-an-xml-attribute-using-xpath

**Comment by nkals722** [comment]
I am not sure this helps / applies to the field mapping for this plugin.

adding @href or [@href] after something doesn't fix it.

If the XML is this:
https://dl.dropboxusercontent.com/spa/1andjyel235zr3w/2wjk5_1s.png

What would the xpath be to get the href attribute of that link xml tag? using @ didn't do anything.

https://dl.dropboxusercontent.com/spa/1andjyel235zr3w/vk1ebdvn.png
