### ISSUE TITLE
Error: Could not create post: Content, title, and excerpt are empty.

### ISSUE THREAD

**Issue by wisefool** [tlovett1/feed-pull#35]
Hi,

Trying to use your plugin to pull in this feed:
http://tickets.courttheatre.org/feed/events/

Every record fails, giving me the error I put as the subject for each record. I've tried simplifying the field mapping, changing the post type to standard post (was trying to create event records)

The XML file looks fine, there's definitely data in the XPaths I'm using, but still I can't create posts because it says the above error.

Any suggestions?

Edit: Just noticing that this is probably worth mentioning too: I am using a node called DirectLink in the XML which is a url formatted link to a page for the guid. However, every record I am trying to insert says:

Status	: Attempting to update post with guid Array

It's seeing an array for the guid, not the node value. Using a different node did not change it.

Thanks.

**Comment by wisefool** [comment]
Update: Sorry, I resolved the issue.

**Comment by kevinliuzzo** [comment]
How did you resolve the issue? I would like to know because I'm getting the same thing and am currently at a loss as how to fix it.
